### PR TITLE
Alternative API

### PR DESCRIPTION
**Pull request by fregante**
This won’t read a file synchronously on load unless that’s what the user wants.

### CODE REVIEW

**Comment by zeke** [comment]
👏

**Comment by zeke** [comment]
```
❯ np patch
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 javascript-yellow 1.0.3 published 🎉
```

**Comment by fregante** [comment]
Wait wait wait that's a breaking change 😂

**Comment by zeke** [comment]
Oh no this is gonna be the next #leftpad

**Comment by zeke** [comment]
Trying to undo, but npm is hanging and failing.

```
❯ npm unpublish javascript-yellow@1.0.4
npm ERR! unpublish Failed to update data
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "javascript-yellow@1.0.4"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code E500

npm ERR! "javascript-yellow status = 403" : javascript-yellow
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zeke/zeke/javascript-yellow/npm-debug.log
```

**Pull request merged**
